# docker-compose build --build-arg USERNAME_REPOSITORY=<bitbucketusername> --build-arg PASSWORD_REPOSITORY=<bitbucketpassword> --build-arg WORKSPACE_PATH="/ecom-api_master" --build-arg MY_WORKSPACE="."
# WORKSPACE_PATH="/ecom-api_master" MY_WORKSPACE="." MY_WORKSPACE="." docker-compose run --rm test
version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - .docker/mongodb/database:/data/db